variables:
  MAVEN_OPTS: "-Dhttps.protocols=TLSv1.2 -Dmaven.repo.local=$CI_PROJECT_DIR/.m2/repository -Dorg.slf4j.simpleLogger.log.org.apache.maven.cli.transfer.Slf4jMavenTransferListener=WARN -Dorg.slf4j.simpleLogger.showDateTime=true -Djava.awt.headless=true"
  MAVEN_CLI_OPTS: "--batch-mode --errors --fail-at-end --show-version -DinstallAtEnd=true -DdeployAtEnd=true"


image: "maven:3.6.3-jdk-8"

maven-dev:
  except:
    - 'master'
  script:
    - 'mvn versions:set -DnewVersion=1.5.2-SNAPSHOT'
    - 'mvn versions:update-child-modules'
    - 'mvn clean deploy -s ci_settings.xml'
  after_script:
    - 'sh docs_upload.sh'
  artifacts:
    paths:
      - '*/target/*version-*.jar'
    expire_in: 2 days

maven-job:
  only:
    - 'master'
  script:
    - 'mvn versions:set -DnewVersion=1.5.2'
    - 'mvn versions:update-child-modules'
    - 'mvn clean deploy -s ci_settings.xml'
  after_script:
    - 'sh docs_upload.sh'
  artifacts:
    paths:
      - '*/target/*.jar'
