<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <groupId>com.tomkeuper.spigot.versionsupport</groupId>
    <artifactId>versionsupport</artifactId>
    <packaging>pom</packaging>
    <version>1.6.4</version>

    <properties>
        <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
        <project.reporting.outputEncoding>UTF-8</project.reporting.outputEncoding>
    </properties>

    <modules>
        <module>sounds_version</module>
        <module>material_version</module>

        <module>block_version</module>
        <module>block_v1_8_R3</module>
        <module>block_v1_9_R2</module>
        <module>block_v1_10_R1</module>
        <module>block_v1_11_R1</module>
        <module>block_v1_12_R1</module>
        <module>block_v1_13_R2</module>
        <module>block_v1_14_R1</module>
        <module>block_v1_15_R1</module>
        <module>block_v1_16_R1</module>
        <module>block_v1_16_R2</module>
        <module>block_v1_16_R3</module>
        <module>block_v1_17_R1</module>
        <module>block_v1_18_R1</module>
        <module>block_v1_18_R2</module>
        <module>block_common</module>

        <module>itemstack_version</module>
        <module>itemstack_common</module>
        <module>itemstack_v1_8_R3</module>
        <module>itemstack_v1_9_R2</module>
        <module>itemstack_v1_10_R1</module>
        <module>itemstack_v1_11_R1</module>
        <module>itemstack_v1_12_R1</module>
        <module>itemstack_v1_13_R2</module>
        <module>itemstack_v1_14_R1</module>
        <module>itemstack_v1_16_R1</module>
        <module>itemstack_v1_15_R1</module>
        <module>itemstack_v1_16_R2</module>
        <module>itemstack_v1_16_R3</module>
        <module>itemstack_v1_17_R1</module>
        <module>itemstack_v1_18_R1</module>
        <module>itemstack_v1_18_R2</module>
        <module>itemstack_v1_19_R1</module>
        <module>itemstack_v1_19_R3</module>

        <module>title_version</module>
        <module>titlecommon</module>
        <module>title_v1_8_R3</module>
        <module>title_v1_9_R2</module>
        <module>title_v1_10_R1</module>
        <module>title_v1_12_R1</module>
        <module>title_v1_11_R1</module>
        <module>title_v1_13_R2</module>
        <module>title_v1_14_R1</module>
        <module>title_v1_15_R1</module>
        <module>title_v1_16_R1</module>
        <module>title_v1_16_R2</module>
        <module>title_v1_16_R3</module>
        <module>title_v1_17_R1</module>
        <module>title_v1_18_R1</module>
        <module>title_v1_19_R3</module>

        <module>chat_version</module>
        <module>chat_common</module>
        <module>chat_v1_8_R3</module>
        <module>chat_v1_12_R1</module>

        <module>cmd-version</module>
        <module>cmd_common</module>
        <module>cmd_v1_8_R3</module>
        <module>cmd_v1_9_R2</module>
        <module>cmd_v1_10_R1</module>
        <module>cmd_v1_11_R1</module>
        <module>cmd_v1_12_R1</module>
        <module>cmd_v1_13_R2</module>
        <module>cmd_v1_14_R1</module>
        <module>cmd_v1_15_R1</module>
        <module>cmd_v1_16_R1</module>
        <module>cmd_v1_16_R2</module>
        <module>cmd_v1_16_R3</module>
        <module>cmd_v1_17_R1</module>
        <module>cmd_v1_18_R1</module>

        <module>particle_common</module>
        <module>particle_version</module>
        <module>particle-v1_8_R3</module>
        <module>particle_v1_9_R2</module>
        <module>particle_v1_10_R1</module>
        <module>particle_v1_11_R1</module>
        <module>particle_v1_12_R1</module>
        <module>particle_v1_13_R2</module>
        <module>particle_v1_14_R1</module>
        <module>particle_v1_15_R1</module>
        <module>particle_v1_16_R1</module>
        <module>particle_v1_16_R2</module>
        <module>particle_v1_16_R3</module>
        <module>particle_v1_17_R1</module>
        <module>particle_v1_18_R1</module>

        <module>player_npc_common</module>
        <module>player_npc_v1_12_R1</module>
        <module>player-npc-version</module>
        <module>player_npc_v1_13_R2</module>
        <module>player_npc_v1_14_R1</module>
        <module>player_npc_v1_15_R1</module>
        <module>player_npc_v1_16_R1</module>
        <module>player_npc_v1_16_R2</module>
        <module>player_npc_v1_16_R3</module>
        <module>player_npc_v1_17_R1</module>
        <module>player_npc_v1_18_R1</module>

        <module>player_utils_common</module>
        <module>player_utils_version</module>
        <module>player_utils_v1_8_R3</module>
        <module>player_utils_v1_9_R2</module>
        <module>player_utils_v1_10_R1</module>
        <module>player_utils_v1_11_R1</module>
        <module>player_utils_v1_12_R1</module>
        <module>player_utils_v1_13_R2</module>
        <module>player_utils_v1_14_R1</module>
        <module>player_utils_v1_15_R1</module>
        <module>player_utils_v1_16_R3</module>
        <module>player_utils_v1_17_R1</module>
        <module>player_utils_v1_18_R1</module>
        <module>player_utils_v1_19_R3</module>
        <module>particle_v1_19_R1</module>
        <module>block_v1_19_R1</module>
    </modules>

    <pluginRepositories>
        <pluginRepository>
            <!-- This is a temporary reference as the Maven Shade plugin
                that supports Java 17 is not released yet -->
            <id>maven-snapshots</id>
            <url>https://repository.apache.org/content/repositories/snapshots/</url>
        </pluginRepository>
    </pluginRepositories>

    <repositories>
        <repository>
            <id>nms-repo</id>
            <url>https://repo.codemc.io/repository/nms/</url>
        </repository>
        <repository>
            <id>spigotmc-repo</id>
            <url>https://hub.spigotmc.org/nexus/content/repositories/snapshots/</url>
        </repository>
    </repositories>

    <dependencies>
        <dependency>
            <groupId>org.jetbrains</groupId>
            <artifactId>annotations</artifactId>
            <version>22.0.0</version>
            <scope>provided</scope>
        </dependency>
    </dependencies>

    <build>
        <extensions>
            <extension>
                <groupId>org.apache.maven.wagon</groupId>
                <artifactId>wagon-ftp</artifactId>
                <version>1.0-beta-6</version>
            </extension>
        </extensions>
        <plugins>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-compiler-plugin</artifactId>
                <version>3.8.1</version>
                <configuration>
                    <source>8</source>
                    <target>8</target>
                </configuration>
            </plugin>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-javadoc-plugin</artifactId>
                <version>3.1.1</version>
                <configuration>
                    <show>public</show>
                    <nohelp>true</nohelp>
                </configuration>
                <executions>
                    <execution>
                        <id>javadoc-jar</id>
                        <phase>deploy</phase>
                        <goals>
                            <goal>jar</goal>
                        </goals>
                    </execution>
                </executions>
            </plugin>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-deploy-plugin</artifactId>
                <version>3.1.1</version>
                <executions>
                    <execution>
                        <id>default-deploy</id>
                        <phase>deploy</phase>
                        <goals>
                            <goal>deploy</goal>
                        </goals>
                    </execution>
                </executions>
            </plugin>
        </plugins>
    </build>
    <reporting>
        <plugins>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-javadoc-plugin</artifactId>
            </plugin>
        </plugins>
    </reporting>


    <distributionManagement>
        <repository>
            <id>bedwars-repo</id>
            <name>Release Maven Repository</name>
            <url>https://repo.tomkeuper.com/repository/releases/</url>
        </repository>
        <snapshotRepository>
            <id>bedwars-repo</id>
            <name>Snapshot Maven Repository</name>
            <url>https://repo.tomkeuper.com/repository/snapshots/</url>
        </snapshotRepository>
    </distributionManagement>
</project>